"""estrutura inicial: usuarios, livros, avaliacoes e favoritos

Revision ID: 78393eb49277
Revises: 
Create Date: 2026-09-03 22:23:24.066616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78393eb49277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=170), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index('idx_authors_name', ['name'], unique=False)

    op.create_table('genres',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('books',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('release_year', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('publisher', sa.String(length=150), nullable=True),
    sa.Column('page_count', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('author_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('genre_id', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('release_year IS NULL OR release_year BETWEEN 1400 AND 2200', name='ck_books_year'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn13'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('idx_books_title', ['title'], unique=False)
        batch_op.create_index('idx_books_year', ['release_year'], unique=False)

    op.create_table('favorites',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('book_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.create_table('reviews',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('book_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('has_spoilers', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('consumed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('rating IS NOT NULL OR body IS NOT NULL', name='ck_reviews_nota_ou_texto'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0.5 AND rating <= 5.0 AND MOD(rating * 10, 5) = 0)', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_reviews_user_book')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('idx_reviews_book_created', ['book_id', 'created_at'], unique=False)

    op.create_table('comments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('review_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('parent_comment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_review', ['review_id', 'created_at'], unique=False)

    op.create_table('review_likes',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('review_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # Ajustado a mao. O autogenerate emitia um `drop_index` antes de cada
    # `drop_table`; no MySQL isso falha com o erro 1553 ("needed in a foreign
    # key constraint"), porque um indice composto que comeca pela coluna da FK
    # e adotado pelo proprio MySQL como indice da FK. O `drop_table` ja remove
    # os indices da tabela, entao as chamadas eram redundantes E quebravam.
    #
    # Ordem da folha para a raiz: quem tem FK cai antes de quem e referenciado.
    for tabela in (
        "review_likes",
        "comments",
        "favorites",
        "reviews",
        "books",
        "users",
        "authors",
        "genres",
    ):
        op.drop_table(tabela)
